### ISSUE TITLE
Literate Programming link goes to a missing page

### ISSUE THREAD

**Issue by ivan-antonyuck** [axiros/docutools#2]
Literate Programming link goes to a missing page

**Comment by axgkl** [comment]
which one?

**Comment by ivan-antonyuck** [comment]
Sorry, this one: 
Most notable feature: Literate Programming, i.e. dynamic code execution - tightly integrated within the mkdocs framework.

In the Readme.md

**Comment by axgkl** [comment]
aaargh. The first link... 
Even had a link checker running, digging through all created html - in the docs folder :-)

=> Thanks Ivan!
